runtime: nodejs20

instance_class: F2

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.65

env_variables:
  NODE_ENV: "production"
  DATABASE_URL: "postgresql://nomutalk_user:NomuTalk2026!Secure@localhost/nomutalk?host=/cloudsql/nomutalk-889bd:asia-northeast3:nomutalk-db"
  LAW_OPEN_API_KEY: "1637swsw"

beta_settings:
  cloud_sql_instances: "nomutalk-889bd:asia-northeast3:nomutalk-db"

vpc_access_connector:
  name: "projects/nomutalk-889bd/locations/asia-northeast3/connectors/nomutalk-connector"
  egress_setting: all-traffic
